List<String> categoryList = [
  'Arts and Crafts',
  'Automotive',
  'Baby Care',
  'Bags and Luggage',
  'Beauty and Personal Care',
  'Book and Stationery',
  'Car and Moterbike Accessories',
  'Computers and Accessories',
  'Digital Subscription',
  'Electronics and Appliances',
  'Fashion (Men, Women, Kids)',
  'Health and Household',
  'Home and Furniture',
  'Home and Kitchen',
  'Industrial and Scientific',
  'Mobiles, Tablets & Accessories',
  'Movies, Music & Video Games',
  'Other',
  'Pet Supplies',
  'Software',
  'Sports and Fitness',
  'Tools and Home Improvement',
  'Toys and Games',
];
