allprojects {
    repositories {
        google()
        mavenCentral()
    }
    configurations.all {
        resolutionStrategy {
            force 'com.google.android.gms:play-services-ads:25.4.0'
            force 'com.google.android.gms:play-services-ads-lite:25.0.0'
            force 'com.google.android.play:core:1.10.3'
        }
    }
}

ext {
    FirebaseSDKVersion = "34.16.0"
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
